--CREATE DATABASE IF NOT EXISTS transactions;
--USE transactions;
--
--CREATE TABLE IF NOT EXISTS transactions (
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    amount DECIMAL(10,2) NOT NULL,
--    description TEXT NOT NULL
--);
